#pragma once

#include <Common/auto_OksEngine.MapRigidBodyToRenderGeometry.hpp>
#include <Common/auto_OksEngine.Position3D.hpp>
#include <Common/auto_OksEngine.Position2D.hpp>
#include <Common/auto_OksEngine.Scale2D.hpp>
#include <Common/auto_OksEngine.Rotation3D.hpp>
#include <Common/auto_OksEngine.Up.hpp>
#include <Common/auto_OksEngine.Width.hpp>
#include <Common/auto_OksEngine.Height.hpp>
#include <Common/auto_OksEngine.Active.hpp>
#include <Common/auto_OksEngine.ChildEntity.hpp>
#include <Common/auto_OksEngine.ChildEntities.hpp>
#include <Common/auto_OksEngine.Name.hpp>
#include <Common/auto_OksEngine.Text.hpp>
#include <Common/auto_OksEngine.Completed.hpp>
#include <Common/auto_OksEngine.BinaryData.hpp>
#include <Common/auto_OksEngine.Direction3D.hpp>
#include <Common/FramesCounter/auto_OksEngine.Components.hpp>
#include <Common/Clock/auto_OksEngine.Clock.hpp>